[build]
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.61.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.61.0"
  HUGO_ENV = "staging"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.61.0"
  HUGO_ENV = "staging"
