[[main]]
  name = "文档"
  url = "/docs/"
  identifier = "docs"
  weight = 10

[[main]]
  name = "官方文档"
  url = "https://pay.weixin.qq.com/wiki/doc/api/sl.html"
  identifier = "blog"
  weight = 30

[[main]]
  name = "官方社区"
  url = "https://developers.weixin.qq.com/community/pay"
  identifier = "community"
  weight = 40
